#ifndef QDRIVEINFO_GLOBAL_H
#define QDRIVEINFO_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(QDRIVEINFO_LIBRARY)
#  define QDRIVEINFO_EXPORT Q_DECL_EXPORT
#else
#  define QDRIVEINFO_EXPORT Q_DECL_IMPORT
#endif

#endif // QDRIVEINFO_GLOBAL_H
